#!/usr/bin/env bash

set -e

# Define the path to your NixOS configuration directory
NIXOS_CONFIG_DIR="/etc/nixos"
NIXOS_CONFIG="$NIXOS_CONFIG_DIR/configuration.nix"

# Change to the NixOS configuration directory
pushd "$NIXOS_CONFIG_DIR"


# Check if there are any changes
if git diff --quiet '*.nix'; then
    echo "No changes detected, exiting."
    exit 0
fi

# Autoformat your nix files
sudo alejandra . &>/dev/null \
  || ( sudo alejandra . ; echo "formatting failed!" && exit 1)

# Shows your changes
git diff -U0 '*.nix'

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo nixos-rebuild switch &>nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)

# Commit all changes with the generation metadata
sudo git commit -am "update"

popd
